language: python
sudo: false
python:
- '2.7'
script:
- rm README.md
- rm fabfile.py
before_deploy:
- gzip -9 data/export/data.csv
deploy:
  provider: s3
  access_key_id: AKIAIWQKYAETOQ2N7CBQ
  secret_access_key:
    secure: mQzm9qfEXWajnhQw+uWKZopl9qrF0xplwqMMcjcR06DZ70ohbdWoFY/jZ9AULDzPATEeOtxkkVbG1Qr8zQrvGdoJeEWk0KCWe7TxCXBsdU08jKKtJhFDFpiVEwZL9norcHkxQKEZO6IVl/cX9LWuPtINs7sqiCVidt9PlQk+/7o=
  bucket: lensnola
  upload-dir: state-salaries
  detect_encoding: true
  skip_cleanup: true
  acl: public_read
  on:
    repo: TheLens/StateSalaries
    branch: master
