language: python
sudo: false
python:
- '2.7'
script:
- rm README.md
- rm fabfile.py
before_deploy:
- rm -rf scripts
- rm -rf citysalaries/templates
- mv citysalaries/static/* . # Move to /neworleans/
- gzip -9 data/export/data.csv
- gzip -9 data/export/highest-paid.csv
- gzip -9 data/export/departments.txt
- gzip -9 data/export/offices.txt
- gzip -9 data/export/positions.txt
- mv data/export/data.csv.gz data/export/data.csv
- mv data/export/highest-paid.csv.gz data/export/highest-paid.csv
- mv data/export/departments.txt.gz data/export/departments.txt
- mv data/export/offices.txt.gz data/export/offices.txt
- mv data/export/positions.txt.gz data/export/positions.txt
deploy:
  provider: s3
  access_key_id: AKIAIWQKYAETOQ2N7CBQ
  secret_access_key:
    secure: mQzm9qfEXWajnhQw+uWKZopl9qrF0xplwqMMcjcR06DZ70ohbdWoFY/jZ9AULDzPATEeOtxkkVbG1Qr8zQrvGdoJeEWk0KCWe7TxCXBsdU08jKKtJhFDFpiVEwZL9norcHkxQKEZO6IVl/cX9LWuPtINs7sqiCVidt9PlQk+/7o=
  bucket: salaries.thelensnola.org
  endpoint: salaries.thelensnola.org.s3-website-us-west-2.amazonaws.com
  region: us-west-2
  upload-dir: louisiana
  detect_encoding: true
  skip_cleanup: true
  acl: public_read
  on:
    repo: TheLens/statesalaries
    branch: develop
